chore: test python integration tests

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -95,117 +95,116 @@ jobs:
   setup:
     uses: looker-open-source/reusable-actions/.github/workflows/supported-versions.yml@main
 
-#  skip all current python versions that don't work in GitHub tasks for integration tests
-#  integration:
-#    needs: [unit,setup]
-#    name: Integration - ${{ matrix.os }} / Looker.${{ matrix.looker }}
-#    env:
-#      TOX_JUNIT_OUTPUT_NAME: ${{ matrix.os }}.Looker-${{ matrix.looker }}.py3.x
-#      LOOKERSDK_CLIENT_ID: ${{ secrets.LOOKERSDK_CLIENT_ID }}
-#      LOOKERSDK_CLIENT_SECRET: ${{ secrets.LOOKERSDK_CLIENT_SECRET }}
-#    runs-on: ${{ matrix.os }}-latest
-#    defaults:
-#      run:
-#        shell: bash
-#        working-directory: python/
-#
-#    strategy:
-#      matrix:
-#        os:
-#          - ubuntu
-#        looker: ${{ fromJson(needs.setup.outputs.matrix_json) }}
-#        # Integ tests on versions 22.12 and beyond intermittently fail CIs - disable for now.
-#        # New release version to be added manually after integration tests have been verified to pass locally.
-#        exclude:
-#          - looker: 22_12
-#          - looker: 22_14
-#          - looker: 22_16
-#
-#          # TODO uncomment `include:` when either macos or windows works to satisfaction.
-#          #include:
-#          # TODO: macos matrix leg is functional but it takes ~20 minutes (compared
-#          # to ~4 minutes for ubuntu) because docker install takes ~5 minutes
-#          # and docker pull takes ~10 minutes. We can probably figure out how to
-#          # cache the docker install but hopefully github will soon have docker
-#          # available pre-installed on macos so not worth the effort now.
-#          # Regarding docker pull ... it would be nice if there's a way to cache
-#          # only some layers of the image on the runner but we don't want to cache
-#          # the final layer(s) with Looker IP. This would speed up docker pull on
-#          # all OSs.
-#          #- os: macos
-#          #  python-version: 3.9
-#          #  looker: '7_20'
-#          # TODO: currently can't run linux containers on windows.
-#          # Pending new windows server version
-#          # https://github.com/actions/virtual-environments/issues/1143#issuecomment-698797524
-#          #- os: windows
-#          #  python-version: 3.9
-#          #  looker: '7_20'
-#    steps:
-#      - name: Repo Checkout
-#        uses: actions/checkout@v2
-#
-#      - name: Set up Cloud SDK
-#        uses: google-github-actions/setup-gcloud@v0.2.0
-#        with:
-#          project_id: ${{ secrets.GCP_PROJECT_ID }}
-#          service_account_key: ${{ secrets.GCP_AR_READER_SA_KEY }}
-#          export_default_credentials: true
-#
-#      - name: Authenticate Artifact Repository
-#        run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet
-#
-#      - name: Install docker on macos
-#        if: ${{ matrix.os == 'macos' }}
-#        uses: docker-practice/actions-setup-docker@v1
-#        with:
-#          docker_channel: stable
-#          docker_buildx: false
-#          docker_cli_experimental: disabled
-#
-#      - name: Bump docker for mac memory
-#        if: ${{ matrix.os == 'macos' }}
-#        run: |
-#          osascript -e 'quit app "Docker"'
-#          sed -i'.original' -e's/  "memoryMiB" : 2048/  "memoryMiB" : 8192/' ~/Library/Group\ Containers/group.com.docker/settings.json
-#          open -g /Applications/Docker.app
-#          # re-run docker startup logic from docker-practice/actions-setup-docker action
-#          sleep 60
-#          i=0
-#          while ! docker system info &>/dev/null; do
-#          (( i++ == 0 )) && printf %s '-- Waiting for Docker to finish starting up...' || printf '.'
-#          sleep 1
-#          done
-#          (( i )) && printf '\n'
-#          echo "-- Docker is ready."
-#
-#      - name: Pull and run Looker docker image
-#        # TODO: can we cache some layers of the image for faster download?
-#        # we probably don't want to cache the final image for IP security...
-#        run: |
-#          docker pull --quiet us-west1-docker.pkg.dev/cloud-looker-sdk-codegen-cicd/looker/${{ matrix.looker }}
-#          # set $LOOKER_OPTS to --no-ssl if we want to turn off ssl
-#          docker run --name looker-sdk-codegen-ci -d -p 10000:9999 -p 20000:19999 us-west1-docker.pkg.dev/cloud-looker-sdk-codegen-cicd/looker/${{ matrix.looker }}
-#          docker logs -f looker-sdk-codegen-ci --until=30s &
-#
-#      - name: Install Tox and any other packages
-#        run: |
-#          python -m pip install --upgrade pip
-#          pip install tox
-#
-#      - name: Check that Looker is ready
-#        run: |
-#          ${{ github.workspace }}/.github/scripts/wait_for_looker.sh
-#
-#      - name: Run Integration Tests
-#        run: tox -e integration
-#
-#      - name: Upload pytest test results
-#        if: ${{ always() }}
-#        uses: actions/upload-artifact@v2
-#        with:
-#          name: python-test-results
-#          path: python/results/
+  integration:
+    needs: [unit,setup]
+    name: Integration - ${{ matrix.os }} / Looker.${{ matrix.looker }}
+    env:
+      TOX_JUNIT_OUTPUT_NAME: ${{ matrix.os }}.Looker-${{ matrix.looker }}.py3.x
+      LOOKERSDK_CLIENT_ID: ${{ secrets.LOOKERSDK_CLIENT_ID }}
+      LOOKERSDK_CLIENT_SECRET: ${{ secrets.LOOKERSDK_CLIENT_SECRET }}
+    runs-on: ${{ matrix.os }}-latest
+    defaults:
+      run:
+        shell: bash
+        working-directory: python/
+
+    strategy:
+      matrix:
+        os:
+          - ubuntu
+        looker: ${{ fromJson(needs.setup.outputs.matrix_json) }}
+        # Integ tests on versions 22.12 and beyond intermittently fail CIs - disable for now.
+        # New release version to be added manually after integration tests have been verified to pass locally.
+        exclude:
+          - looker: 22_12
+          - looker: 22_14
+          - looker: 22_16
+
+          # TODO uncomment `include:` when either macos or windows works to satisfaction.
+          #include:
+          # TODO: macos matrix leg is functional but it takes ~20 minutes (compared
+          # to ~4 minutes for ubuntu) because docker install takes ~5 minutes
+          # and docker pull takes ~10 minutes. We can probably figure out how to
+          # cache the docker install but hopefully github will soon have docker
+          # available pre-installed on macos so not worth the effort now.
+          # Regarding docker pull ... it would be nice if there's a way to cache
+          # only some layers of the image on the runner but we don't want to cache
+          # the final layer(s) with Looker IP. This would speed up docker pull on
+          # all OSs.
+          #- os: macos
+          #  python-version: 3.9
+          #  looker: '7_20'
+          # TODO: currently can't run linux containers on windows.
+          # Pending new windows server version
+          # https://github.com/actions/virtual-environments/issues/1143#issuecomment-698797524
+          #- os: windows
+          #  python-version: 3.9
+          #  looker: '7_20'
+    steps:
+      - name: Repo Checkout
+        uses: actions/checkout@v2
+
+      - name: Set up Cloud SDK
+        uses: google-github-actions/setup-gcloud@v0.2.0
+        with:
+          project_id: ${{ secrets.GCP_PROJECT_ID }}
+          service_account_key: ${{ secrets.GCP_AR_READER_SA_KEY }}
+          export_default_credentials: true
+
+      - name: Authenticate Artifact Repository
+        run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet
+
+      - name: Install docker on macos
+        if: ${{ matrix.os == 'macos' }}
+        uses: docker-practice/actions-setup-docker@v1
+        with:
+          docker_channel: stable
+          docker_buildx: false
+          docker_cli_experimental: disabled
+
+      - name: Bump docker for mac memory
+        if: ${{ matrix.os == 'macos' }}
+        run: |
+          osascript -e 'quit app "Docker"'
+          sed -i'.original' -e's/  "memoryMiB" : 2048/  "memoryMiB" : 8192/' ~/Library/Group\ Containers/group.com.docker/settings.json
+          open -g /Applications/Docker.app
+          # re-run docker startup logic from docker-practice/actions-setup-docker action
+          sleep 60
+          i=0
+          while ! docker system info &>/dev/null; do
+          (( i++ == 0 )) && printf %s '-- Waiting for Docker to finish starting up...' || printf '.'
+          sleep 1
+          done
+          (( i )) && printf '\n'
+          echo "-- Docker is ready."
+
+      - name: Pull and run Looker docker image
+        # TODO: can we cache some layers of the image for faster download?
+        # we probably don't want to cache the final image for IP security...
+        run: |
+          docker pull --quiet us-west1-docker.pkg.dev/cloud-looker-sdk-codegen-cicd/looker/${{ matrix.looker }}
+          # set $LOOKER_OPTS to --no-ssl if we want to turn off ssl
+          docker run --name looker-sdk-codegen-ci -d -p 10000:9999 -p 20000:19999 us-west1-docker.pkg.dev/cloud-looker-sdk-codegen-cicd/looker/${{ matrix.looker }}
+          docker logs -f looker-sdk-codegen-ci --until=30s &
+
+      - name: Install Tox and any other packages
+        run: |
+          python -m pip install --upgrade pip
+          pip install tox
+
+      - name: Check that Looker is ready
+        run: |
+          ${{ github.workspace }}/.github/scripts/wait_for_looker.sh
+
+      - name: Run Integration Tests
+        run: tox -e integration
+
+      - name: Upload pytest test results
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: python-test-results
+          path: python/results/
 
   twine:
     needs: unit #integration
